### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by nodesocket** [toshimaru/ec2-price#2]
Would be awesome to have a `--format json` flag, which returns json instead of a table.

**Comment by nodesocket** [comment]
What do you think? Could we implement it?

**Comment by toshimaru** [comment]
I couldn't imagine any use cases for the JSON format. why do you want to get JSON format??

**Comment by nodesocket** [comment]
I'd like to use ec2 prices in another node.js cli app, and want to avoid trying to parse the table output.

**Comment by toshimaru** [comment]
gotcha, then go ahead. will be nice!

**Comment by loisaidasam** [comment]
👍

**Comment by loisaidasam** [comment]
Done. Instead of `--format json` it's just `--json` or `-j` for short.

**Comment by nodesocket** [comment]
Can you upload to npm please? Thanks.

**Comment by toshimaru** [comment]
Hey, @nodesocket @loisaidasam , I've just published v0.4.0 on npm. Thanks!
